### ISSUE TITLE
Fail to run `make run-holochain` step in devhub-gui

### ISSUE THREAD

**Issue by zippy** [mjbrisebois/node-holochain-backdrop#1]
```
devhub-gui$ make run-holochain
npx holochain-backdrop --admin-port 35678 --config holochain/config.yaml -v
Running cleanup...

Stopping Holochain...
TypeError: Cannot read properties of undefined (reading 'keystore_path')
    at Holochain._setup (/home/eric/code/metacurrency/holochain/devhub-gui/node_modules/@whi/holochain-backdrop/src/holochain.js:128:45)
    at new Holochain (/home/eric/code/metacurrency/holochain/devhub-gui/node_modules/@whi/holochain-backdrop/src/holochain.js:54:7)
    at Command.<anonymous> (/home/eric/code/metacurrency/holochain/devhub-gui/node_modules/@whi/holochain-backdrop/bin/hc-backdrop-cli.js:139:23)
    at Command.listener [as _actionHandler] (/home/eric/code/metacurrency/holochain/devhub-gui/node_modules/@whi/holochain-backdrop/node_modules/commander/lib/command.js:488:17)
    at /home/eric/code/metacurrency/holochain/devhub-gui/node_modules/@whi/holochain-backdrop/node_modules/commander/lib/command.js:1227:65
    at /home/eric/code/metacurrency/holochain/devhub-gui/node_modules/@whi/holochain-backdrop/node_modules/commander/lib/command.js:1141:33
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Command.parseAsync (/home/eric/code/metacurrency/holochain/devhub-gui/node_modules/@whi/holochain-backdrop/node_modules/commander/lib/command.js:923:5)
    at async main (/home/eric/code/metacurrency/holochain/devhub-gui/node_modules/@whi/holochain-backdrop/bin/hc-backdrop-cli.js:189:5)
```
Here is the holochain config.yaml

```
$ more holochain/config.yaml 
environment_path: /home/eric/code/metacurrency/holochain/devhub-gui/holochain/databases
keystore_path: /home/eric/code/metacurrency/holochain/devhub-gui/holochain/lair
passphrase_service:
  type: danger_insecure_from_config
  passphrase: testing
admin_interfaces:
  - driver:
      type: websocket
      port: 35678
network:
  network_type: quic_bootstrap
  transport_pool:
    - type: quic
```

**Comment by mjbrisebois** [comment]
This module won't assume it has the authority to remove or override old configs so it may require manual resetting bumping versions.  One of the recent updates upgraded to Lair 0.1.0 which changed the config from

```yaml
environment_path: String
keystore_path: String
passphrase_service:
  type: danger_insecure_from_config
  passphrase: testing
admin_interfaces:
  - driver:
      type: websocket
      port: 35678
network:
  network_type: quic_bootstrap
  transport_pool:
    - type: quic
```

to

```yaml
environment_path: String
keystore:
  type: lair_server
  keystore_path: String
  danger_passphrase_insecure_from_config: ""
  connection_url: String
admin_interfaces:
  - driver:
      type: websocket
      port: 35678
network:
  network_type: quic_bootstrap
  transport_pool:
    - type: quic
db_sync_strategy: Fast
```
